// <auto-generated />
using System;
using MarketTools.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketTools.Infrastructure.Migrations
{
    [DbContext(typeof(MainAppDbContext))]
    [Migration("20231205120820_AddMainTemplateSettingsFlag")]
    partial class AddMainTemplateSettingsFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoresponderConnectionRatingAutoresponderTemplate", b =>
                {
                    b.Property<int>("TemplatesId")
                        .HasColumnType("integer");

                    b.Property<int>("RatingsRating")
                        .HasColumnType("integer");

                    b.Property<int>("RatingsConnectionId")
                        .HasColumnType("integer");

                    b.HasKey("TemplatesId", "RatingsRating", "RatingsConnectionId");

                    b.HasIndex("RatingsRating", "RatingsConnectionId");

                    b.ToTable("AutoresponderConnectionRatingAutoresponderTemplate");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AppIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderBanWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlackListId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BlackListId");

                    b.ToTable("AutoresponderBanWords");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderBlackList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AutoresponderBlackLists");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.ToTable("AutoresponderCells");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AutoresponderColumns");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderColumnBindPosition", b =>
                {
                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int?>("ColumnId")
                        .HasColumnType("integer");

                    b.HasKey("Position", "TemplateId");

                    b.HasIndex("ColumnId");

                    b.HasIndex("TemplateId");

                    b.ToTable("AutoresponderColumnBindPositions");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderConnection", b =>
                {
                    b.Property<int>("SellerConnectionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("SellerConnectionId");

                    b.ToTable("AutoresponderConnections");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderConnectionRating", b =>
                {
                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("integer");

                    b.Property<int?>("BindAutoresponerBlackListId")
                        .HasColumnType("integer");

                    b.HasKey("Rating", "ConnectionId");

                    b.HasIndex("BindAutoresponerBlackListId");

                    b.HasIndex("ConnectionId");

                    b.ToTable("AutoresponderConnectionRatings");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderRecommendationProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackArticle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("FeedbackProductName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MarketplaceName")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendationArticle")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("RecommendationProductName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AutoresponderRecommendationProducts");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AutoresponderTemplates");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderTemplateArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("AutoresponderTemplateArticles");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderTemplateSettings", b =>
                {
                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<bool>("AsMainTemplate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSkipEmptyFeedbacks")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSkipWithTextFeedbacks")
                        .HasColumnType("boolean");

                    b.HasKey("TemplateId");

                    b.ToTable("AutoresponderTemplateSettings");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.SellerConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SellerConnections");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SellerConnection");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.OzonOpenApiSellerConnection", b =>
                {
                    b.HasBaseType("MarketTools.Domain.Entities.SellerConnection");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("OzonOpenApiSellerConnection");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.WbOpenApiSellerConnection", b =>
                {
                    b.HasBaseType("MarketTools.Domain.Entities.SellerConnection");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("SellerConnections", t =>
                        {
                            t.Property("Token")
                                .HasColumnName("WbOpenApiSellerConnection_Token");
                        });

                    b.HasDiscriminator().HasValue("WbOpenApiSellerConnection");
                });

            modelBuilder.Entity("AutoresponderConnectionRatingAutoresponderTemplate", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AutoresponderTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketTools.Domain.Entities.AutoresponderConnectionRating", null)
                        .WithMany()
                        .HasForeignKey("RatingsRating", "RatingsConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AutoresponderConnectionRatingAutoresponderTemplate_Autores~1");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderBanWord", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AutoresponderBlackList", "BlackList")
                        .WithMany("BanWords")
                        .HasForeignKey("BlackListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlackList");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderBlackList", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", "User")
                        .WithMany("AutoresponderBlackLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderCell", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AutoresponderColumn", "Column")
                        .WithMany("Cells")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderColumn", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", "User")
                        .WithMany("AutoreponderColumns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderColumnBindPosition", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AutoresponderColumn", "Column")
                        .WithMany("BindPositions")
                        .HasForeignKey("ColumnId");

                    b.HasOne("MarketTools.Domain.Entities.AutoresponderTemplate", "Template")
                        .WithMany("BindPositions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderConnection", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.SellerConnection", "SellerConnection")
                        .WithOne("AutoresponderConnection")
                        .HasForeignKey("MarketTools.Domain.Entities.AutoresponderConnection", "SellerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SellerConnection");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderConnectionRating", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AutoresponderBlackList", "BindAutoresponerBlackList")
                        .WithMany()
                        .HasForeignKey("BindAutoresponerBlackListId");

                    b.HasOne("MarketTools.Domain.Entities.AutoresponderConnection", "Connection")
                        .WithMany("Ratings")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BindAutoresponerBlackList");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderRecommendationProduct", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", "User")
                        .WithMany("AutoresponderRecommendationProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderTemplate", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", "User")
                        .WithMany("AutoresponderTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderTemplateArticle", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AutoresponderTemplate", "Template")
                        .WithMany("Articles")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderTemplateSettings", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AutoresponderTemplate", "Template")
                        .WithOne("Settings")
                        .HasForeignKey("MarketTools.Domain.Entities.AutoresponderTemplateSettings", "TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.SellerConnection", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", "User")
                        .WithMany("SellerConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MarketTools.Domain.Entities.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AppIdentityUser", b =>
                {
                    b.Navigation("AutoreponderColumns");

                    b.Navigation("AutoresponderBlackLists");

                    b.Navigation("AutoresponderRecommendationProducts");

                    b.Navigation("AutoresponderTemplates");

                    b.Navigation("SellerConnections");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderBlackList", b =>
                {
                    b.Navigation("BanWords");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderColumn", b =>
                {
                    b.Navigation("BindPositions");

                    b.Navigation("Cells");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderConnection", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.AutoresponderTemplate", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("BindPositions");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("MarketTools.Domain.Entities.SellerConnection", b =>
                {
                    b.Navigation("AutoresponderConnection")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
